version: '3'

services:
  hidden-jvc-website:
    container_name: hidden-jvc-website
    build: .
    environment:
      USE_SUB_FOLDER: "0"
      H_CAPTCHA_SITE_KEY: "10000000-ffff-ffff-ffff-000000000001"
    ports:
      - "6565:80"